name: Docker Image CI

on:
  push:
    branches: [ extract-classroom ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build WS
      run: ./gradlew dist
    - name: Build the Docker image
      run: docker build ws --tag thmmniii/http:classroom
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Push the Docker image
      run: docker push thmmniii/digital-classroom:latest
