name: Docker Image CI

on:
  push:
    branches: [ extract-classroom ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build WS
      run: ./gradlew dist
    - name: Build the Docker image
      run: docker build ws --tag thmmniii/http:classroom
    - name: Docker login
      run: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
    - name: Push the Docker image
      run: docker push thmmniii/digital-classroom:latest
